//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdhocManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdhocManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launches the Windows Network Connection Application ähnelt.
        /// </summary>
        internal static string MainForm_Connections_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Connections_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string MainForm_Error {
            get {
                return ResourceManager.GetString("MainForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to stop any existing AdHoc Network? ähnelt.
        /// </summary>
        internal static string MainForm_Exit_Dialog {
            get {
                return ResourceManager.GetString("MainForm_Exit_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Might be empty, but it is not recommended ähnelt.
        /// </summary>
        internal static string MainForm_Password_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Password_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string MainForm_Question {
            get {
                return ResourceManager.GetString("MainForm_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An application restart is required for the settings to take effekt. Restart? ähnelt.
        /// </summary>
        internal static string MainForm_Restart_Required {
            get {
                return ResourceManager.GetString("MainForm_Restart_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set a SSID (max. 32 chars) here or leave empty ähnelt.
        /// </summary>
        internal static string MainForm_SSID_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_SSID_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to setup the SSID and password, please check the process output ähnelt.
        /// </summary>
        internal static string MainForm_Start_SettingsError {
            get {
                return ResourceManager.GetString("MainForm_Start_SettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid SSID ähnelt.
        /// </summary>
        internal static string MainForm_Start_SSIDEmpty {
            get {
                return ResourceManager.GetString("MainForm_Start_SSIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to start the AdHoc Network, please check the process output ähnelt.
        /// </summary>
        internal static string MainForm_Start_StartHostednetworkError {
            get {
                return ResourceManager.GetString("MainForm_Start_StartHostednetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configures and starts the Hosted Network ähnelt.
        /// </summary>
        internal static string MainForm_Start_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to stop the AdHoc Network, please check the process output ähnelt.
        /// </summary>
        internal static string MainForm_Stop_StopHostednetworkError {
            get {
                return ResourceManager.GetString("MainForm_Stop_StopHostednetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stops the Hosted Network ähnelt.
        /// </summary>
        internal static string MainForm_Stop_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unhandled Exception ähnelt.
        /// </summary>
        internal static string MainForm_UnhandledException {
            get {
                return ResourceManager.GetString("MainForm_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to load the network adapter list ähnelt.
        /// </summary>
        internal static string MainForm_UpdateAdapters_Exception {
            get {
                return ResourceManager.GetString("MainForm_UpdateAdapters_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP: ähnelt.
        /// </summary>
        internal static string NetworkAdapterNode_IP {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Received: ähnelt.
        /// </summary>
        internal static string NetworkAdapterNode_Received {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send: ähnelt.
        /// </summary>
        internal static string NetworkAdapterNode_Send {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed: ähnelt.
        /// </summary>
        internal static string NetworkAdapterNode_Speed {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_Speed", resourceCulture);
            }
        }
    }
}
