//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdhocManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdhocManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launches the Windows Network Connection Application.
        /// </summary>
        internal static string MainForm_Connections_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Connections_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_Error {
            get {
                return ResourceManager.GetString("MainForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop any existing AdHoc Network?.
        /// </summary>
        internal static string MainForm_Exit_Dialog {
            get {
                return ResourceManager.GetString("MainForm_Exit_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Might be empty, but it is not recommended.
        /// </summary>
        internal static string MainForm_Password_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Password_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MainForm_Question {
            get {
                return ResourceManager.GetString("MainForm_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application restart is required for the settings to take effekt. Restart?.
        /// </summary>
        internal static string MainForm_Restart_Required {
            get {
                return ResourceManager.GetString("MainForm_Restart_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a SSID (max. 32 chars) here or leave empty.
        /// </summary>
        internal static string MainForm_SSID_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_SSID_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to setup the SSID and password, please check the process output.
        /// </summary>
        internal static string MainForm_Start_SettingsError {
            get {
                return ResourceManager.GetString("MainForm_Start_SettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid SSID.
        /// </summary>
        internal static string MainForm_Start_SSIDEmpty {
            get {
                return ResourceManager.GetString("MainForm_Start_SSIDEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the AdHoc Network, please check the process output.
        /// </summary>
        internal static string MainForm_Start_StartHostednetworkError {
            get {
                return ResourceManager.GetString("MainForm_Start_StartHostednetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures and starts the Hosted Network.
        /// </summary>
        internal static string MainForm_Start_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to stop the AdHoc Network, please check the process output.
        /// </summary>
        internal static string MainForm_Stop_StopHostednetworkError {
            get {
                return ResourceManager.GetString("MainForm_Stop_StopHostednetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the Hosted Network.
        /// </summary>
        internal static string MainForm_Stop_Tooltip {
            get {
                return ResourceManager.GetString("MainForm_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string MainForm_UnhandledException {
            get {
                return ResourceManager.GetString("MainForm_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the network adapter list.
        /// </summary>
        internal static string MainForm_UpdateAdapters_Exception {
            get {
                return ResourceManager.GetString("MainForm_UpdateAdapters_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP:.
        /// </summary>
        internal static string NetworkAdapterNode_IP {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received:.
        /// </summary>
        internal static string NetworkAdapterNode_Received {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send:.
        /// </summary>
        internal static string NetworkAdapterNode_Send {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        internal static string NetworkAdapterNode_Speed {
            get {
                return ResourceManager.GetString("NetworkAdapterNode_Speed", resourceCulture);
            }
        }
    }
}
